name: common-setup
description: "Checkout, setup Node.js, cache npm, and install backend/api dependencies"
inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Cache npm and node_modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          backend/api/node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-npm-${{ hashFiles('backend/api/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-npm-

    - name: Install API dependencies
      working-directory: ./backend/api
      shell: bash
      run: |
        if [ -f backend/api/package-lock.json ]; then
          npm ci --prefer-offline --no-audit --no-fund || npm install --no-audit --no-fund
        else
          npm install --no-audit --no-fund
        fi
