name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME_TEST }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Check required secrets
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
        run: |
          missing=false
          if [ -z "$MYSQL_ROOT_PASSWORD" ]; then echo "Required secret MYSQL_ROOT_PASSWORD is missing"; missing=true; fi
          if [ -z "$DB_USER" ]; then echo "Required secret DB_USER is missing"; missing=true; fi
          if [ -z "$DB_PASS" ]; then echo "Required secret DB_PASS is missing"; missing=true; fi
          if [ -z "$DB_NAME_TEST" ]; then echo "Required secret DB_NAME_TEST is missing"; missing=true; fi
          if [ "$missing" = true ]; then echo "One or more required secrets are missing. Set them in repo Settings → Secrets and variables → Actions."; exit 1; fi

      - name: Install mysql client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 --silent; then
              echo "MySQL is up";
              break;
            fi
            echo "Waiting for MySQL... ($i)";
            sleep 2;
          done

      - name: Create CI DB user and grant privileges
        env:
          ROOT_PASS: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME_TEST }}
        run: |
          echo "Creating CI DB user if not exists and granting privileges..."
          # Use the mysql client to create user and grant privileges on the test DB
          mysql -h 127.0.0.1 -P 3306 -uroot -p"$ROOT_PASS" -e "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%'; FLUSH PRIVILEGES;"

      - name: Cache npm and node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            blog/api/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('blog/api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-

      - name: Install API dependencies
        working-directory: ./blog/api
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Run tests
        working-directory: ./blog/api
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
        run: npm test
